-- MySQL Script generated by MySQL Workbench
-- Tue Aug 26 21:52:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeringasistenciaasistencia

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `area` VARCHAR(30) NOT NULL,
  `clave` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rut_UNIQUE` ON `mydb`.`Usuario` (`rut` ASC) VISIBLE;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `mydb`.`Usuario` (`correo` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`Usuario` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `accion` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_idx` ON `mydb`.`Asistencia` (`idUsuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`Asistencia` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `mydb`.`Asistencia` (`idUsuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;